version: '3.8'

services:
  hello:
    image: nvcr.io/nvidia/pytorch:24.10-py3
    working_dir: /workspace
    volumes:
      - ./:/workspace

    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      python main.py
      --epochs 1
      --seed 42

